### ISSUE TITLE
There is no correct instruction on how to get mathbench dataset

### ISSUE THREAD

**Issue by vivek-dani** [open-compass/MathBench#10]
There is not mathbench folder present in git clone https://github.com/open-compass/opencompass , as per instruction it should have been present.

Also looking at documentation here: https://opencompass.readthedocs.io, mathbench dataset is not present in https://github.com/open-compass/opencompass/releases/download/0.2.2.rc1/OpenCompassData-core-20240207.zip
unzip OpenCompassData-core-20240207.zip

There is no instruction on how to get mathbench dataset

**Comment by airaria** [comment]
I find it on the release page https://github.com/open-compass/MathBench/releases/tag/v0.1.0

**Comment by tonysy** [comment]
Feel free to re-open if needed.
