### ISSUE TITLE
readme report 8-shot result but opencompass only support 4-shot

### ISSUE THREAD

**Issue by Daemon-ser** [open-compass/MathBench#23]
<img width="787" alt="image" src="https://github.com/user-attachments/assets/9c8092fe-feea-4368-be4b-b0a02eeb8111">
<img width="651" alt="image" src="https://github.com/user-attachments/assets/3f08d08a-bcb5-47dc-a1b7-7f625d00ca12">

**Comment by liushz** [comment]
Sorry for the confusion.
This is a BUG and already fixed. Please update OpenCompass to the latest version, the latest version use:
`configs/datasets/MathBench/mathbench_2024_gen_19e486.py` for MathBench.
