### ISSUE TITLE
The paper is not found in the main page.

### ISSUE THREAD

**Issue by zhimin-z** [open-compass/MathBench#4]
![image](https://github.com/open-compass/MathBench/assets/8592144/be7010d5-3b36-4894-9ddd-fd79041291ab)
After clicking on the paper option on the project page, it will redirect me to the same web page as above. It seems the corresponding link is missing...

**Comment by liushz** [comment]
Thank you for your interest in MathBench. We are pleased to inform you that the arXiv version of the MathBench paper is currently undergoing internal review and will be released in the near future. We appreciate your patience and look forward to sharing our work with the research community soon.

**Comment by liushz** [comment]
Thank you for your patience, the paper for MathBench can be found in:
https://arxiv.org/abs/2405.12209

**Comment by zhimin-z** [comment]
> Thank you for your patience, the paper for MathBench can be found in: https://arxiv.org/abs/2405.12209

Got it! Thanks!
